sonar.projectKey=DevWebClients
sonar.projectName=Portail Clients DevWeb
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=sqp_86078113108b2e1e71cdaadc449357c146c6e0de
sonar.sourceEncoding=UTF-8