sonar.projectKey=DevWeb-Clients
sonar.projectName=DevWeb-Clients
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=sqp_3637b64a0ee1f4b618a69778c8422e43960e817e
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
sonar.qualitygate.wait=true

# Configuration pour l'analyse de branches
sonar.branch.name=main

# Configuration Pull Request decoration (si supporté)
# sonar.pullrequest.key=${{ github.event.pull_request.number }}
# sonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
# sonar.pullrequest.base=${{ github.event.pull_request.base.ref }}